### ISSUE TITLE
AMO release 2 review

### ISSUE THREAD

**Issue by Trim** [Trim/avoid-google-search-redirects#1]
Here are comments I received after Mozilla review:

> Reviewer:
erosman
>
>Comments:
>Thank you for your contribution.
>
>Please note the following for the next update:
>1) Please use globs to limit the pages script is inserted into.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts
>
>2) Please make your add-on listing more elaborate. Your summary should briefly explain what the add-on does, so that even people without knowledge about your add-on and its services can understand. The description should give details on the add-on features, how to configure and if not apparent then how to use it. The listing should also contain one or more screenshots.

**Comment by roryokane** [comment]
I was going to make a pull request with these changes to address the first point of feedback:

#### [`manifest.json`](https://github.com/Trim/avoid-google-search-redirects/blob/master/manifest.json)

~~~json
      "matches": ["*://*.google.*/"],
~~~

#### [`override-google-rwt.js`](https://github.com/Trim/avoid-google-search-redirects/blob/master/override-google-rwt.js)

~~~javascript
if (window.wrappedJSObject.rwt) {
    window.wrappedJSObject.rwt = exportFunction(function() { }, window);
}
~~~

But actually, that wouldn’t work. [`matches`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts#matches) takes an array of match patterns. And according to the docs for [Match patterns](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/match_patterns), `*` is only supported at the beginning of the hostname. So you can do `"*://*.google.com/"`, but not `"*://*.google.*/"`.

Google is one of the few sites for which it would be difficult to enumerate all of the TLDs. There are `google.com`, `google.co.uk`, `google.fr`, and dozens more domains. A domain is probably added or removed every few years.

I would prefer that this extension uses `matches` because that would reassure me that this extension couldn’t possibly mess up other websites or steal my data on them after a malicious update. But I don’t blame you if you can’t find the list of domains you would need to use `matches`.

If you don’t enumerate all Google domains, I think the most precise you can get for `matches` is `"*://*/"`. That is a little more strict than `"<all_urls>"` in that it only matches URLs with the `http` or `https` protocols, not URLs with the `file`, `ftp`, or `app` protocols.

**Comment by Trim** [comment]
> If you don’t enumerate all Google domains, I think the most precise you can get for matches is "*://*/". That is a little more strict than "<all_urls>" in that it only matches URLs with the http or https protocols, not URLs with the file, ftp, or app protocols.

Oh, I didn't expect that `*://` will only target HTTP and HTTPS, thanks for the information.

I was thinking about enumerating all Google domains, it should not be so complicated and it will be easy to add new domains for every one. So, there's one domain by country which will make around 150 entries to test and add.

Mmhh, I think I could create a shell script which will try every "www.google." + TLD possible and save the result on my disk. Current root TLD are available [here](https://www.iana.org/domains/root/db).

**Comment by roryokane** [comment]
Yes, a shell script to iterate over possible domains should work.

As [this article](http://www.zdnet.com/article/the-list-of-google-domains-is-very-misleading/) suggests, to make sure that the domains you find are really owned by Google and not by an impersonator, you can run `whois` on the domain and check that the registrar is MarkMonitor Inc. But checking that may not be necessary for this add-on, given that disabling search redirects on fake sites shouldn’t cause any security problems.

**Comment by Trim** [comment]
Closing as I'll archive the project.
